idf_component_register(
    SRCS 
        "src/hal/dc_motor/dc_motor.cpp"
        "src/hal/bts7960/bts7960.cpp"
        "src/hal/bts7960/bts7960_position.cpp"
        "src/hal/bts7960/bts7960_pot_position.cpp"
        "src/hal/servo/servo.cpp"
        "src/hal/stepper/stepper.cpp"
        "src/mcal/wifi/WiFi.cpp"
        "src/mcal/mqtt/MQTT.cpp"
        "src/mcal/nvs/NVS.cpp"
    INCLUDE_DIRS 
        "inc"
        "inc/hal/dc_motor"
        "inc/hal/bts7960"
        "inc/hal/pot"
        "inc/hal/pid"
        "inc/hal/servo"
        "inc/hal/stepper"
        "inc/mcal/wifi"
        "inc/mcal/mqtt"
        "inc/mcal/nvs"
    REQUIRES
        driver    
        freertos
        nvs_flash
        esp_common
        esp_event
        esp_netif
        esp_timer
        esp_adc
        esp_wifi
        esp_http_client
        esp_driver_gpio
        esp_driver_uart
        esp_driver_i2c
        esp_driver_ledc
        mqtt
)