idf_component_register(
        SRCS 
                "src/hal/led/led.cpp" 
                "src/hal/button/button.cpp" 
                "src/hal/dc_motor/dc_motor.cpp"
                "src/hal/tcrt5000/TCRT5000.cpp"
                "src/hal/mpu6050/MPU6050.cpp"
                "src/hal/ultrasonic/ultrasonic.cpp"
                "src/hal/servo/servo.cpp"
                "src/hal/pot/pot.cpp"
                "src/mcal/nvs/NVS.cpp"
                "src/mcal/wifi/wifi_sta.cpp"
                "src/mcal/wifi/wifi_ap.cpp"
                "src/mcal/wifi/WiFi.cpp"
                "src/mcal/mqtt/MQTT.cpp"
                "src/mcal/uart/uart.cpp"
        INCLUDE_DIRS 
                "inc"
                "inc/hal/led" 
                "inc/hal/button" 
                "inc/hal/dc_motor"
                "inc/hal/tcrt5000"
                "inc/hal/mpu6050"
                "inc/hal/ultrasonic"
                "inc/hal/servo"
                "inc/hal/pot"
                "inc/mcal/nvs"
                "inc/mcal/wifi"
                "inc/mcal/mqtt"
                "inc/mcal/uart"
        REQUIRES
                driver    
                freertos
                nvs_flash
                esp_common
                esp_event
                esp_netif
                esp_timer
                esp_adc
                esp_wifi
                mqtt
                esp_http_client
)
